#!/usr/bin/env bash
# adds a file to 2216-web-01 using a remote ssh call
if [ $# == 4 ]
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
