#!/usr/bin/env bash
# nginx would not start / restart because sites-enabled/default was not a symbolink to sites-avaliable/default
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm /run/nginx.pid
