#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely. but cannot be closed
trap 'echo I am invincible!!!' SIGTERM
a=0
while [ $a -lt 1 ]; do
    echo "To infinity and beyond"
    sleep 2
done
