#!/usr/bin/env bash
#prints "Holberton School" 10 times in stdout but on the 9th iteration prints "hi"
iter=0
while [ $iter -lt 10 ]; do
    if [ $iter == 9 ]
    then
        echo $"Hi"
    fi
    echo $"Holberton School"
    iter=$((iter+1))
done
