#!/usr/bin/env bash
# configures Ubunut server with new web ip for facebook and local ip
sudo cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost$/127.0.0.2 localhost/" ~/hosts.new
echo -e "\n8.8.8.8 facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
